spring:
  application:
    name: Writing Assistant

  datasource:
    url: jdbc:mysql://localhost:3306/writingassistant?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.xiaowa.writingassistant.entity

server:
  port: 8081

vivo:
  api:
    domain: "api-ai.vivo.com.cn"
    app-id: "2025301523"
    app-key: "wqRFrShBGxbfyOMx"
    completions-uri: "/vivogpt/completions"
    model-name: "vivo-BlueLM-TB-Pro"

ai:
  service:
    base-url: "http://localhost:8081"
